// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muqdmvkapsxrsgdkfoxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11cWRtdmthcHN4cnNnZGtmb3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNDI5MTQsImV4cCI6MjA5NDkxODkxNH0.PnYJzWS5FuybLBSNV3FbiaRp95-7h0WR0PpiTpJgxIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});